name: Add Release Assets

on:
    release:
        types: [published]

jobs:
    asset:
        runs-on: ${{matrix.operating-system}}
        strategy:
            matrix:
                operating-system: [ ubuntu-latest ]
                php: [ "5.4", "5.6", "7.0", "7.4" ]

        name: Upload Release Assets
        steps:
            - uses: olegtarasov/get-tag@v2
              id: tagName

            - uses: octokit/request-action@v2.x
              id: getLatestRelease
              with:
                route: GET /repos/:repository/releases/${{ steps.tagName.outputs.tag }}
                repository: ${{ github.repository }}
                env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: nanasess/setup-php@v3.0.4
              with:
                php-version: ${{ matrix.php }}

            - name: Install Dependencies
              uses: nick-invision/retry@v1
              with:
                timeout_minutes: 10
                max_attempts: 3
                command: composer install

            - name: Create Archive
              run: |
                zip --junk-paths google-api-php-client-${tagName}-PHP${matrix.php}.zip .
              env:
                tagName: ${{ steps.tagName.outputs.tag }}

            - name: Upload Release Archive
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              with:
                upload_url: ${{ fromJson(steps.getLatestRelease.outputs.data).upload_url }}
                asset_path: ./google-api-php-client-${tagName}-PHP${matrix.php}.zip
                asset_name: google-api-php-client-${tagName}-PHP${matrix.php}.zip
                asset_content_type: application/zip
